openapi: 3.0.0
info:
  title: Book
  version: 2.0
paths:
  /books:
    get:
      summary: Get list of books
      operationId: getBooks
      responses:
        '200':
          description: List of management user information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookList'

    post:
      summary: Create a book
      operationId: createBook

      requestBody:
        description: Book to be created
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'

      responses:
        '200' :
          description: Details of the newly created book
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'

  /books/{book}:
    get:
      summary: Gets details of a specific book
      operationId: getBook
      parameters:
      - name: book
        in: path
        description: Identfier of the book
        required: true
        schema:
          type: string

      responses:
        '200' :
          description: Book information for the given book identifier.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'

    put:
      summary:
      operationId: updateBook
      parameters:
      - name : book
        in : path
        description: Identifier of the book to be updated.
        required: true
        schema:
          type: string

      requestBody:
        description: Management user to
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookUpdate'

      responses:
        '200' :
          description: Indicates that local user information updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'

    delete:
      summary: Delete a book
      operationId: deleteBook
      parameters:
        - name : book
          in : path
          description: Identfier of the book
          required: true
          schema:
            type: string

      responses:
        '204' :
          description: Indicates that the book was successfully deleted

components:
  schemas:
    Book:
      type: object
      properties:
        title:
          description: Book title
          type: string
        isbn:
          description: Book ISBN
          type: string
        authors:
          description: Book authors
          type: array
          items:
            type: string

    BookList:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Book'

    BookUpdate:
      type: object
      properties:
        title:
          description: Book title
          type: string
        authors:
          description: Book authors
          type: array
          items:
            type: string